### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by mentix02** [HackerHouseYT/OpenAI-NEAT#5]
After running - 
`$ python gym_solver.py --max-steps=1000 --episodes=10 --generations=50 --render`
I get - 
[2017-01-29 00:37:15,406] Making new env: CartPole-v0
Input Nodes: 4
Output Nodes: 2
Traceback (most recent call last):
  File "gym_solver.py", line 111, in <module>
    train_network(my_env)
  File "gym_solver.py", line 72, in train_network
    pop = population.Population(config_path)
  File "/usr/local/lib/python2.7/dist-packages/neat/population.py", line 17, in __init__
    stagnation = config.stagnation_type(config.stagnation_config, self.reporters)
AttributeError: 'str' object has no attribute 'stagnation_type'

**Comment by atainter** [comment]
Looks like a version issue. Will update it later today.

**Comment by atainter** [comment]
Confirmed version error. `neat-python` v0.9 has some breaking features. I will probably update this to support v0.9 at some point, but for now you can solve this issue by installing v0.8 ` pip install neat-python==0.8 --upgrade`
